Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/BlockComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyLinesAroundAccessModifier:
  Enabled: false

Style/FileName:
  Enabled: false

Style/EmptyLines:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false

Metrics/LineLength:
  Max: 120
